from __future__ import annotations

import dataclasses
import functools
import importlib
import sys
from abc import ABC, abstractmethod
from bdb import BdbQuit
from collections import ChainMap, defaultdict
from contextlib import contextmanager
from decimal import Decimal
from enum import IntEnum
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    DefaultDict,
    Dict,
    Iterable,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
    cast,
    overload,
)
from urllib.error import HTTPError

import eth_utils
from Crypto.Hash import BLAKE2b
from typing_extensions import Literal, TypedDict, get_args, get_origin, get_type_hints

from wake_rs import (
    Abi,
    Account,
    Address,
    Contract,
    Library,
    abi,
    encode_eip712_data,
    encode_eip712_type,
    get_eip712_signing_hash,
    keccak256,
    parse_unit,
    to_checksum_address,
)

from ..utils import StrEnum
from . import hardhat_console
from .blocks import ChainBlocks
from .chain_interfaces import (
    AnvilChainInterface,
    ChainInterfaceAbc,
    GethLikeChainInterfaceAbc,
    HardhatChainInterface,
    SignedAuthorization,
    TxParams,
)
from .globals import (
    chain_interfaces_manager,
    get_config,
    get_coverage_handler,
    get_exception_handler,
)
from .internal import UnknownEvent, read_from_memory
from .json_rpc.communicator import JsonRpcError
from .primitive_types import (
    FixedSizeBytes,
    FixedSizeList,
    Integer,
    bytes32,
    fixed_bytes_map,
    fixed_list_map,
    int_map,
    uint256,
    uint_map,
)
from .pytypes_resolver import resolve_call_error, resolve_error

if TYPE_CHECKING:
    from .transactions import ChainTransactions, TransactionAbc


# selector => (contract_fqn => pytypes_object)
errors: Dict[bytes, Dict[str, Any]] = {}
# selector => (contract_fqn => pytypes_object)
events: Dict[bytes, Dict[str, Any]] = {}
# contract_fqn => contract type
contracts_by_fqn: Dict[str, Any] = {}
# contract_metadata => contract_fqn
contracts_by_metadata: Dict[bytes, str] = {}
# list of pairs of (creation code segments, contract_fqn)
# where creation code segments is a tuple of (length, BLAKE2b hash)
creation_code_index: List[Tuple[Tuple[Tuple[int, bytes], ...], str]] = []
# user defined value type type identifier => underlying type type identifier
user_defined_value_types_index: Dict[str, str] = {}


def get_contracts_by_fqn() -> Dict[str, Any]:
    return contracts_by_fqn


def get_user_defined_value_types_index() -> Dict[str, str]:
    return user_defined_value_types_index


def get_eip712_struct_hash(obj: Any) -> bytes32:
    return keccak256(
        keccak256(encode_eip712_type(obj).encode()) + encode_eip712_data(obj)
    )


class RevertToSnapshotFailedError(Exception):
    pass


class NotConnectedError(Exception):
    pass


class AlreadyConnectedError(Exception):
    pass


class TransactionConfirmationFailedError(Exception):
    pass


class Struct:
    def encode_eip712_type(self) -> str:
        return encode_eip712_type(self)

    def encode_eip712_data(self) -> bytes:
        return encode_eip712_data(self)

    def get_eip712_struct_hash(self) -> bytes32:
        return get_eip712_struct_hash(self)

    def get_eip712_signing_hash(self, domain: Eip712Domain) -> bytes32:
        return get_eip712_signing_hash(self, domain)


class RequestType(StrEnum):
    ACCESS_LIST = "access_list"
    CALL = "call"
    ESTIMATE = "estimate"
    TX = "tx"


def fix_library_abi(args: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    ret = []
    for arg in args:
        # create a shallow copy so that we don't mutate the original ABI,
        # and recursively rebuild only the parts we actually touch
        arg = dict(arg)

        if arg["type"] == "tuple":
            # recurse into tuple components and update them as well
            arg["components"] = fix_library_abi(arg["components"])

        if "internalType" in arg:
            # internalType was added in 0.5.11
            # versions before 0.5.11 are not supported by Wake anyway
            # but we may fetch ABIs generated by an older version of solc through Etherscan
            if arg["internalType"].startswith("contract "):
                # replace contract type with "address" but keep array suffix (if any)
                arg["type"] = arg["type"].replace(
                    arg["type"].split("[", 1)[0], "address"
                )
            elif arg["internalType"].startswith("enum "):
                # replace enum type with "uint8" but keep array suffix (if any)
                arg["type"] = arg["type"].replace(arg["type"].split("[", 1)[0], "uint8")
        ret.append(arg)
    return ret


class Wei(int):
    def __new__(
        cls, value: Union[int, str, Decimal, Wei] = 0, *, unit: Optional[str] = None
    ) -> Wei:
        if isinstance(value, Wei):
            if unit is None:
                return super().__new__(cls, int(value))
            else:
                raise ValueError("unit must be None if value is a Wei object")
        elif isinstance(value, int):
            if unit is None:
                return super().__new__(cls, value)
            else:
                return super().__new__(cls, int(value) * 10 ** parse_unit(unit))
        elif isinstance(value, str):
            if unit is None:
                parts = value.split()
                if len(parts) > 2:
                    raise ValueError(
                        f"Expected either '<amount> <unit>' or '<amount>', got {value!r}"
                    )
                elif len(parts) == 2:
                    count, unit = parts
                    return cls.from_unit(count, unit)
                else:
                    return super().__new__(cls, int(value))
            else:
                multiplied = Decimal(value) * Decimal(10 ** parse_unit(unit))
                if multiplied % 1 != 0:
                    raise ValueError("Value multiplied by unit is not an integer")
                return super().__new__(cls, int(multiplied))
        elif isinstance(value, Decimal):
            if unit is None:
                raise ValueError("unit must be specified if value is a Decimal")
            else:
                multiplied = value * Decimal(10 ** parse_unit(unit))
                if multiplied % 1 != 0:
                    raise ValueError("Value multiplied by unit is not an integer")
                return super().__new__(cls, int(multiplied))
        else:
            raise TypeError(f"Invalid value type: {type(value)}")

    def __repr__(self) -> str:
        return f"Wei({int(self)} wei)"

    def __str__(self) -> str:
        n = int(self)
        if n == 0:
            return "0 wei"
        elif n >= 10**15:
            ether = Decimal(n) / Decimal(10**18)
            if ether % 1 == 0:
                return f"{ether} ether ({n} wei)"
            else:
                rounded = ether.quantize(Decimal("0.001"))
                return f"~{rounded.normalize()} ether ({n} wei)"
        elif n >= 10**6:
            gwei = Decimal(n) / Decimal(10**9)
            if gwei % 1 == 0:
                return f"{gwei} gwei ({n} wei)"
            else:
                rounded = gwei.quantize(Decimal("0.001"))
                return f"~{rounded.normalize()} gwei ({n} wei)"
        else:
            return f"{n} wei"

    def __add__(self, other):
        return Wei(int(self) + int(Wei(other)))

    @classmethod
    def wei(cls, value: Union[int, str, Decimal, Wei]) -> Wei:
        return cls(value, unit="wei")

    @classmethod
    def gwei(cls, value: Union[int, str, Decimal, Wei]) -> Wei:
        return cls(value, unit="gwei")

    @classmethod
    def ether(cls, value: Union[int, str, Decimal, Wei]) -> Wei:
        return cls(value, unit="ether")

    @classmethod
    def from_unit(cls, value: Union[int, str, Decimal, Wei], unit: str) -> Wei:
        return cls(value, unit=unit)

    @classmethod
    def parse(cls, text: str) -> Wei:
        return cls(text)

    def to_wei(self) -> int:
        return int(self)

    def to_gwei(self) -> Decimal:
        return Decimal(self) / Decimal(10**9)

    def to_ether(self) -> Decimal:
        return Decimal(self) / Decimal(10**18)

    def to(self, unit: str) -> Decimal:
        return Decimal(self) / Decimal(10 ** parse_unit(unit))


def ether(value: Union[int, str, Decimal, Wei]) -> Wei:
    return Wei.ether(value)


def gwei(value: Union[int, str, Decimal, Wei]) -> Wei:
    return Wei.gwei(value)


def detect_default_chain() -> Chain:
    if "wake.deployment" in sys.modules and "wake.testing" in sys.modules:
        import wake.deployment
        import wake.testing

        if wake.deployment.chain.connected and wake.testing.chain.connected:
            raise ValueError(
                "Both wake.testing.chain and wake.deployment.chain are connected. Please specify which chain to use."
            )

        if wake.deployment.chain.connected:
            return wake.deployment.chain
        elif wake.testing.chain.connected:
            return wake.testing.chain
        else:
            raise NotConnectedError("`chain` not connected")
    elif "wake.deployment" in sys.modules:
        import wake.deployment

        return wake.deployment.chain
    elif "wake.testing" in sys.modules:
        import wake.testing

        return wake.testing.chain
    else:
        raise NotConnectedError("`chain` not connected")


Eip712Domain = TypedDict(
    "Eip712Domain",
    {
        "name": str,
        "version": str,
        "chainId": int,
        "verifyingContract": Union[Account, Address, str],
        "salt": bytes,
    },
    total=False,
)


def check_connected(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        if not args[0].connected:
            raise NotConnectedError("Not connected to a chain")
        return f(*args, **kwargs)

    return wrapper


_test_accounts_generated_count: int = 0


class Chain(ABC):
    _connected: bool
    _chain_interface: ChainInterfaceAbc
    _accounts: List[Account]
    _accounts_set: Set[Account]  # for faster lookup
    _default_call_account: Optional[Account]
    _default_tx_account: Optional[Account]
    _default_estimate_account: Optional[Account]
    _default_access_list_account: Optional[Account]
    _default_tx_confirmations: int
    _deployed_libraries: DefaultDict[bytes, List[Library]]
    _snapshots: Dict[str, Dict]
    _blocks: ChainBlocks
    _txs: ChainTransactions
    _chain_id: int
    _labels: Dict[Address, str]
    _require_signed_txs: bool
    _fork: Optional[str]
    _forked_chain_id: Optional[int]
    _debug_trace_call_supported: bool
    _client_version: str
    _pytypes_resolvers: DefaultDict[Account, Type[Contract] | None]

    tx_callback: Optional[Callable[[TransactionAbc], None]]

    def __deepcopy__(self, memo):
        return self

    @abstractmethod
    def _connect_setup(
        self, min_gas_price: Optional[int], block_base_fee_per_gas: Optional[int]
    ) -> None:
        ...

    @abstractmethod
    def _connect_finalize(self) -> None:
        ...

    @abstractmethod
    def _new_private_key(self, extra_entropy: bytes = b"") -> bytes:
        ...

    @abstractmethod
    def snapshot(self) -> str:
        ...

    @abstractmethod
    def revert(self, snapshot_id: str) -> None:
        ...

    @abstractmethod
    def _build_transaction(
        self,
        request_type: RequestType,
        params: TxParams,
        arguments: Iterable,
        abi: Optional[Dict],
        block_identifier: Union[int, str],
    ) -> TxParams:
        ...

    @abstractmethod
    def _wait_for_transaction(
        self, tx: TransactionAbc, confirmations: Optional[int]
    ) -> None:
        ...

    @abstractmethod
    def _confirm_transaction(self, tx: TxParams) -> None:
        ...

    @property
    @abstractmethod
    def block_gas_limit(self) -> int:
        ...

    @block_gas_limit.setter
    @abstractmethod
    def block_gas_limit(self, value: int) -> None:
        ...

    @property
    @abstractmethod
    def gas_price(self) -> Wei:
        ...

    @gas_price.setter
    @abstractmethod
    def gas_price(self, value: int) -> None:
        ...

    @property
    @abstractmethod
    def max_priority_fee_per_gas(self) -> Wei:
        ...

    @max_priority_fee_per_gas.setter
    @abstractmethod
    def max_priority_fee_per_gas(self, value: int) -> None:
        ...

    @contextmanager  # pyright: ignore reportGeneralTypeIssues
    @abstractmethod
    def connect(
        self,
        uri: Optional[str] = None,
        *,
        accounts: Optional[int] = None,
        chain_id: Optional[int] = None,
        fork: Optional[str] = None,
        hardfork: Optional[str] = None,
        min_gas_price: Optional[Union[int, str]],
        block_base_fee_per_gas: Optional[Union[int, str]],
    ):
        ...

    def __init__(self):
        self._connected = False
        self._labels = {}

    def _connect(
        self,
        uri: Optional[str] = None,
        *,
        accounts: Optional[int],
        chain_id: Optional[int],
        fork: Optional[str],
        hardfork: Optional[str],
        min_gas_price: Optional[Union[int, str]],
        block_base_fee_per_gas: Optional[Union[int, str]],
    ):
        global _test_accounts_generated_count

        if self._connected:
            raise AlreadyConnectedError("Already connected to a chain")

        if isinstance(min_gas_price, str):
            min_gas_price = Wei.parse(min_gas_price)
        if isinstance(block_base_fee_per_gas, str):
            block_base_fee_per_gas = Wei.parse(block_base_fee_per_gas)

        self._chain_interface = chain_interfaces_manager.get_or_create(
            uri, accounts=accounts, chain_id=chain_id, fork=fork, hardfork=hardfork
        )

        try:
            self._connected = True
            self._client_version = self._chain_interface.get_client_version()
            from .utils import reset_lru_cache

            reset_lru_cache()

            try:
                self._chain_interface.debug_trace_call(
                    {
                        "type": 0,
                    }
                )
                self._debug_trace_call_supported = True
            except (JsonRpcError, HTTPError):
                self._debug_trace_call_supported = False

            self._chain_id = self._chain_interface.get_chain_id()

            # determine the forked chain id (if any)
            # determine the chain hardfork to set the default tx type
            if isinstance(self._chain_interface, AnvilChainInterface):
                info = self._chain_interface.node_info()

                if (
                    "forkConfig" in info
                    and "forkUrl" in info["forkConfig"]
                    and info["forkConfig"]["forkUrl"] is not None
                ):
                    forked_chain_interface = ChainInterfaceAbc.connect(
                        get_config(), info["forkConfig"]["forkUrl"]
                    )
                    try:
                        self._forked_chain_id = forked_chain_interface.get_chain_id()
                    finally:
                        forked_chain_interface.close()
                else:
                    self._forked_chain_id = None
            elif isinstance(
                self._chain_interface,
                (GethLikeChainInterfaceAbc, HardhatChainInterface),
            ):
                if isinstance(self._chain_interface, GethLikeChainInterfaceAbc):
                    self._forked_chain_id = None
                else:
                    metadata = self._chain_interface.hardhat_metadata()
                    if (
                        "forkedNetwork" in metadata
                        and "chainId" in metadata["forkedNetwork"]
                    ):
                        self._forked_chain_id = metadata["forkedNetwork"]["chainId"]
                    else:
                        self._forked_chain_id = None
            else:
                raise NotImplementedError(
                    f"Unknown chain interface type: {type(self._chain_interface)}"
                )

            if block_base_fee_per_gas is not None:
                try:
                    self._chain_interface.set_next_block_base_fee_per_gas(
                        block_base_fee_per_gas
                    )
                except JsonRpcError:
                    pass

            from .transactions import ChainTransactions

            self._txs = ChainTransactions(self)

            self._accounts = [
                Account(acc, self) for acc in self._chain_interface.get_accounts()
            ]

            if len(self._accounts) > _test_accounts_generated_count:
                # generate private keys for accounts without private key
                for i in range(_test_accounts_generated_count, len(self._accounts)):
                    Address.from_mnemonic(
                        "test test test test test test test test test test test junk",
                        path=f"m/44'/60'/0'/0/{i}",
                    )
                _test_accounts_generated_count = len(self._accounts)

            self._accounts_set = set(self._accounts)
            self._snapshots = {}
            self._deployed_libraries = defaultdict(list)
            self._pytypes_resolvers = defaultdict(lambda: None)

            if len(self._accounts) > 0:
                self.set_default_accounts(self._accounts[0])
            else:
                self.set_default_accounts(None)
            self._default_tx_confirmations = 1
            self._blocks = ChainBlocks(self)
            self._fork = fork

            self.tx_callback = None

            self._connect_setup(min_gas_price, block_base_fee_per_gas)

            yield self
        except Exception as e:
            if not isinstance(e, BdbQuit):
                exception_handler = get_exception_handler()
                if exception_handler is not None:
                    exception_handler(*sys.exc_info())
                raise
        finally:
            self._connect_finalize()
            self._connected = False

    @property
    def connected(self) -> bool:
        return self._connected

    @property
    def client_version(self) -> str:
        return self._client_version

    @property
    @check_connected
    def chain_interface(self) -> ChainInterfaceAbc:
        return self._chain_interface

    @property
    @check_connected
    def chain_id(self) -> uint256:
        return uint256(self._chain_id)

    @property
    @check_connected
    def forked_chain_id(self) -> Optional[uint256]:
        return (
            uint256(self._forked_chain_id)
            if self._forked_chain_id is not None
            else None
        )

    @property
    @check_connected
    def accounts(self) -> Tuple[Account, ...]:
        return tuple(self._accounts)

    @property
    @check_connected
    def txs(self) -> ChainTransactions:
        return self._txs

    @property
    @check_connected
    def default_call_account(self) -> Optional[Account]:
        return self._default_call_account

    @default_call_account.setter
    @check_connected
    def default_call_account(self, account: Union[Account, Address, str]) -> None:
        if isinstance(account, Account):
            if account.chain != self:
                raise ValueError("Account is not from this chain")
            self._default_call_account = account
        else:
            self._default_call_account = Account(account, self)

    @property
    @check_connected
    def default_tx_account(self) -> Optional[Account]:
        return self._default_tx_account

    @default_tx_account.setter
    @check_connected
    def default_tx_account(self, account: Union[Account, Address, str]) -> None:
        if isinstance(account, Account):
            if account.chain != self:
                raise ValueError("Account is not from this chain")
            self._default_tx_account = account
        else:
            self._default_tx_account = Account(account, self)

    @property
    @check_connected
    def default_estimate_account(self) -> Optional[Account]:
        return self._default_estimate_account

    @default_estimate_account.setter
    @check_connected
    def default_estimate_account(self, account: Union[Account, Address, str]) -> None:
        if isinstance(account, Account):
            if account.chain != self:
                raise ValueError("Account is not from this chain")
            self._default_estimate_account = account
        else:
            self._default_estimate_account = Account(account, self)

    @property
    @check_connected
    def default_access_list_account(self) -> Optional[Account]:
        return self._default_access_list_account

    @default_access_list_account.setter
    @check_connected
    def default_access_list_account(
        self, account: Union[Account, Address, str]
    ) -> None:
        if isinstance(account, Account):
            if account.chain != self:
                raise ValueError("Account is not from this chain")
            self._default_access_list_account = account
        else:
            self._default_access_list_account = Account(account, self)

    @property
    @check_connected
    def coinbase(self) -> Account:
        return Account(self._chain_interface.get_coinbase(), self)

    @coinbase.setter
    @check_connected
    def coinbase(self, value: Union[Account, Address, str]) -> None:
        if isinstance(value, Account):
            if value.chain != self:
                raise ValueError("Account is not from this chain")
            self._chain_interface.set_coinbase(str(value.address))
        else:
            self._chain_interface.set_coinbase(str(value))

    @property
    @check_connected
    def blocks(self) -> ChainBlocks:
        return self._blocks

    @property
    @check_connected
    def require_signed_txs(self) -> bool:
        return self._require_signed_txs

    @require_signed_txs.setter
    @check_connected
    def require_signed_txs(self, value: bool) -> None:
        self._require_signed_txs = value

    @property
    @check_connected
    def default_tx_confirmations(self) -> int:
        return self._default_tx_confirmations

    @default_tx_confirmations.setter
    @check_connected
    def default_tx_confirmations(self, value: int) -> None:
        if value < 0:
            raise ValueError("Invalid transaction confirmations value")
        self._default_tx_confirmations = value

    @contextmanager
    def change_automine(self, automine: bool):
        if not self._connected:
            raise NotConnectedError("Not connected to a chain")
        automine_was = self._chain_interface.get_automine()
        self._chain_interface.set_automine(automine)
        try:
            yield
        except Exception as e:
            if not isinstance(e, BdbQuit):
                exception_handler = get_exception_handler()
                if exception_handler is not None:
                    exception_handler(*sys.exc_info())
                raise
        finally:
            self._chain_interface.set_automine(automine_was)

    @property
    @check_connected
    def automine(self) -> bool:
        return self._chain_interface.get_automine()

    @automine.setter
    @check_connected
    def automine(self, value: bool) -> None:
        self._chain_interface.set_automine(value)

    @check_connected
    def set_next_block_base_fee_per_gas(self, value: Union[int, str, Decimal]) -> None:
        self._chain_interface.set_next_block_base_fee_per_gas(Wei(value))

    @check_connected
    def set_next_block_timestamp(self, timestamp: int) -> None:
        self._chain_interface.set_next_block_timestamp(timestamp)

    @check_connected
    def set_min_gas_price(self, value: Union[int, str, Decimal]) -> None:
        wei = Wei(value)
        self._chain_interface.set_min_gas_price(wei)
        self.gas_price = wei

    @check_connected
    def set_default_accounts(self, account: Union[Account, Address, str, None]) -> None:
        if isinstance(account, Account):
            if account.chain != self:
                raise ValueError("Account is not from this chain")
        elif account is not None:
            account = Account(account, self)

        self._default_call_account = account
        self._default_tx_account = account
        self._default_estimate_account = account
        self._default_access_list_account = account

    @check_connected
    def reset(self) -> None:
        self._chain_interface.reset()

    @check_connected
    def update_accounts(self):
        self._accounts = [
            Account(acc, self) for acc in self._chain_interface.get_accounts()
        ]
        self._accounts_set = set(self._accounts)

    @check_connected
    def mine(self, timestamp_change: Optional[Callable[[int], int]] = None) -> None:
        if timestamp_change is not None:
            block_info = self._chain_interface.get_block("latest")
            assert "timestamp" in block_info
            last_timestamp = int(block_info["timestamp"], 16)
            timestamp = timestamp_change(last_timestamp)
        else:
            timestamp = None

        self._chain_interface.mine(timestamp)

    @check_connected
    def mine_many(
        self, num_blocks: int, timestamp_change: Optional[int] = None
    ) -> None:
        self._chain_interface.mine_many(num_blocks, timestamp_change)

    @contextmanager
    def snapshot_and_revert(self):
        snapshot_id = self.snapshot()
        try:
            yield
        except Exception as e:
            if not isinstance(e, BdbQuit):
                exception_handler = get_exception_handler()
                if exception_handler is not None:
                    exception_handler(*sys.exc_info())
                raise
        finally:
            self.revert(snapshot_id)

    @overload
    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: Literal["call"],
        return_tx: Literal[False] = False,
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> bytes:
        ...

    @overload
    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: Literal["tx"] = "tx",
        return_tx: Literal[False] = False,
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> Contract:
        ...

    @overload
    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: Literal["estimate"],
        return_tx: Literal[False] = False,
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> int:
        ...

    @overload
    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: Literal["access_list"],
        return_tx: Literal[False] = False,
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> Tuple[Dict[Address, List[int]], int]:
        ...

    @overload
    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: Literal["tx"] = "tx",
        return_tx: Literal[True],
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> TransactionAbc[Contract]:
        ...

    def deploy(
        self,
        creation_code: bytes,
        *,
        request_type: RequestType = "tx",
        return_tx: bool = False,
        from_: Optional[Union[Account, Address, str]] = None,
        value: Union[int, str] = 0,
        gas_limit: Optional[Union[int, Literal["max", "auto"]]] = None,
        gas_price: Optional[Union[int, str]] = None,
        max_fee_per_gas: Optional[Union[int, str]] = None,
        max_priority_fee_per_gas: Optional[Union[int, str]] = None,
        access_list: Optional[
            Union[Dict[Union[Account, Address, str], List[int]], Literal["auto"]]
        ] = None,
        block: Optional[
            Union[int, Literal["latest", "pending", "earliest", "safe", "finalized"]]
        ] = None,
        confirmations: Optional[int] = None,
        revert_on_failure: bool = True,
    ) -> Union[
        bytes,
        Contract,
        int,
        Tuple[Dict[Address, List[int]], int],
        TransactionAbc[Contract],
    ]:
        return Contract._execute(
            self,
            request_type,
            creation_code.hex(),
            [],
            return_tx,
            Contract,
            from_,
            None,
            value,
            gas_limit,
            gas_price,
            max_fee_per_gas,
            max_priority_fee_per_gas,
            access_list,
            type,
            block,
            confirmations,
            revert_on_failure,
        )

    def _convert_to_web3_type(self, value: Any) -> Any:
        if dataclasses.is_dataclass(value):
            return tuple(
                self._convert_to_web3_type(getattr(value, f.name))
                for f in dataclasses.fields(value)
            )
        elif isinstance(value, list):
            return [self._convert_to_web3_type(v) for v in value]
        elif isinstance(value, tuple):
            return tuple(self._convert_to_web3_type(v) for v in value)
        elif isinstance(value, Account):
            if value.chain != self:
                raise ValueError("Account must belong to this chain")
            return str(value.address)
        elif isinstance(value, Address):
            return str(value)
        elif hasattr(value, "selector") and isinstance(value.selector, bytes):
            instance = value.__self__
            return bytes.fromhex(str(instance.address)[2:]) + value.selector
        else:
            return value

    def _parse_console_log_data(self, data: bytes):
        selector = data[:4]

        if selector not in hardhat_console.abis:
            raise ValueError(f"Unknown selector: {selector.hex()}")
        abi = hardhat_console.abis[selector]

        output_types = [
            eth_utils.abi.collapse_if_tuple(cast(Dict[str, Any], arg))
            for arg in fix_library_abi(abi)
        ]
        decoded_data = list(Abi.decode(output_types, data[4:]))
        for i in range(len(decoded_data)):
            if abi[i]["type"] == "address":
                decoded_data[i] = Account(decoded_data[i], self)

        if len(decoded_data) == 1:
            decoded_data = decoded_data[0]

        return decoded_data

    def _convert_from_web3_type(
        self, tx: Optional[TransactionAbc], value: Any, expected_type: Type
    ) -> Any:
        origin = get_origin(expected_type)

        if isinstance(expected_type, type(None)):
            return None
        elif isinstance(origin, type) and issubclass(origin, list):
            return origin(
                [
                    self._convert_from_web3_type(tx, v, get_args(expected_type)[0])
                    for v in value
                ]
            )
        elif origin is tuple:
            return tuple(
                self._convert_from_web3_type(tx, v, t)
                for v, t in zip(value, get_args(expected_type))
            )
        elif dataclasses.is_dataclass(expected_type):
            assert isinstance(value, tuple)

            resolved_types = get_type_hints(
                expected_type,  # pyright: ignore reportGeneralTypeIssues
            )
            field_types = [
                resolved_types[field.name]
                for field in dataclasses.fields(expected_type)
                if field.init
            ]
            assert len(value) == len(field_types)
            converted_values = [
                self._convert_from_web3_type(tx, v, t)
                for v, t in zip(value, field_types)
            ]
            return expected_type(*converted_values)
        elif isinstance(expected_type, type):
            if issubclass(expected_type, Contract):
                return expected_type(value, self)
            elif issubclass(expected_type, Account):
                return Account(value, self)
            elif issubclass(expected_type, IntEnum):
                return expected_type(value)
        return value

    def _process_return_data(
        self, tx: Optional[TransactionAbc], output: bytes, abi: Dict, return_type: Type
    ):
        output_types = [
            eth_utils.abi.collapse_if_tuple(cast(Dict[str, Any], arg))
            for arg in fix_library_abi(abi["outputs"])
        ]
        decoded_data = Abi.decode(output_types, output)
        if isinstance(decoded_data, (list, tuple)) and len(decoded_data) == 1:
            decoded_data = decoded_data[0]
        return self._convert_from_web3_type(tx, decoded_data, return_type)

    def _process_console_logs(self, trace_output: List[Dict[str, Any]]) -> List:
        hardhat_console_address = bytes.fromhex(
            "000000000000000000636F6e736F6c652e6c6f67"
        )
        console_logs = []
        for trace in trace_output:
            if "action" in trace and "to" in trace["action"]:
                to = trace["action"]["to"]
                if to.startswith("0x"):
                    to = to[2:]
                if bytes.fromhex(to) == hardhat_console_address:
                    input = trace["action"]["input"]
                    if input.startswith("0x"):
                        input = input[2:]
                    console_logs.append(
                        self._parse_console_log_data(bytes.fromhex(input))
                    )
        return console_logs

    def _process_console_logs_from_debug_trace(
        self, debug_trace: Dict[str, Any]
    ) -> List:
        hardhat_console_address = Address("0x000000000000000000636F6e736F6c652e6c6f67")
        console_logs = []
        for trace in debug_trace["structLogs"]:
            if trace["op"] == "STATICCALL":
                addr = Address(int(trace["stack"][-2], 16))
                if addr == hardhat_console_address:
                    args_offset = int(trace["stack"][-3], 16)
                    args_size = int(trace["stack"][-4], 16)
                    data = bytes(
                        read_from_memory(args_offset, args_size, trace["memory"])
                    )
                    console_logs.append(self._parse_console_log_data(data))

        return console_logs

    def _send_transaction(
        self, tx_params: TxParams, from_: Optional[Union[Account, Address, str]]
    ) -> str:
        assert "from" in tx_params

        if self._chain_id in {56, 97}:
            # BSC doesn't support access lists and tx type
            tx_params.pop("type", None)
            tx_params.pop("accessList", None)

        if self.require_signed_txs:
            if isinstance(from_, (Account, Address)):
                key = from_.private_key
            elif from_ is None and self._default_tx_account is not None:
                key = self._default_tx_account.private_key
            else:
                key = None

            tx_params["nonce"] = self._chain_interface.get_transaction_count(
                str(tx_params["from"])
            )

            tx_params["from"] = to_checksum_address(tx_params["from"])

            if "to" in tx_params:
                tx_params["to"] = to_checksum_address(tx_params["to"])

            self._confirm_transaction(tx_params)

            if Account(tx_params["from"], self) in self._accounts_set:
                try:
                    tx_hash = self._chain_interface.send_transaction(tx_params)
                except (ValueError, JsonRpcError) as e:
                    try:
                        tx_hash = e.args[0]["data"]["txHash"]
                    except Exception:
                        raise e from None
            elif key is not None:
                signed_tx = Account(tx_params["from"], self).sign_transaction(tx_params)
                try:
                    tx_hash = self._chain_interface.send_raw_transaction(signed_tx)
                except (ValueError, JsonRpcError) as e:
                    try:
                        tx_hash = e.args[0]["data"]["txHash"]
                    except Exception:
                        raise e from None
            else:
                raise ValueError(
                    f"Private key for account {tx_params['from']} not known and is not owned by the connected client either."
                )
        else:
            if isinstance(self.chain_interface, AnvilChainInterface):
                try:
                    tx_hash = self.chain_interface.send_unsigned_transaction(tx_params)
                except (ValueError, JsonRpcError) as e:
                    try:
                        tx_hash = e.args[0]["data"]["txHash"]
                    except Exception:
                        raise e
            else:
                sender = Account(tx_params["from"], self)

                tx_params["nonce"] = self._chain_interface.get_transaction_count(
                    str(tx_params["from"])
                )

                with _signer_account(sender):
                    try:
                        tx_hash = self._chain_interface.send_transaction(tx_params)
                    except (ValueError, JsonRpcError) as e:
                        try:
                            tx_hash = e.args[0]["data"]["txHash"]
                        except Exception:
                            raise e

        self._txs.register_tx(tx_hash)

        return tx_hash

    @check_connected
    def _call(
        self,
        abi: Optional[Dict],
        arguments: Iterable,
        params: TxParams,
        return_type: Type,
        block: Union[int, str],
    ) -> Any:
        if isinstance(block, int) and block < 0:
            block = self._chain_interface.get_block_number() + 1 + block

        tx_params = self._build_transaction(
            RequestType.CALL, params, arguments, abi, block
        )
        try:
            coverage_handler = get_coverage_handler()
            if coverage_handler is not None and self._debug_trace_call_supported:
                ret = self._chain_interface.debug_trace_call(tx_params, block)
                coverage_handler.add_coverage(tx_params, block, self, ret)

                ret_value = ret["returnValue"]
                if ret_value.startswith("0x"):
                    ret_value = ret_value[2:]
                output = bytes.fromhex(ret_value)
                if ret["failed"]:
                    raise resolve_error(
                        self,
                        block,
                        None,
                        output,
                        lambda: self._chain_interface.debug_trace_call(
                            tx_params, block, {"tracer": "callTracer"}
                        ),
                    )
            else:
                output = self._chain_interface.call(tx_params, block)
        except JsonRpcError as e:
            raise resolve_call_error(self, tx_params, block, e) from None

        if abi is None:
            return output

        return self._process_return_data(None, output, abi, return_type)

    @check_connected
    def _estimate(
        self,
        abi: Optional[Dict],
        arguments: Iterable,
        params: TxParams,
        block: Union[int, str],
    ) -> int:
        if isinstance(block, int) and block < 0:
            block = self._chain_interface.get_block_number() + 1 + block

        tx_params = self._build_transaction(
            RequestType.ESTIMATE, params, arguments, abi, block
        )
        try:
            return self._chain_interface.estimate_gas(tx_params, block)
        except JsonRpcError as e:
            raise resolve_call_error(self, tx_params, block, e) from None

    @check_connected
    def _access_list(
        self,
        abi: Optional[Dict],
        arguments: Iterable,
        params: TxParams,
        block: Union[int, str],
    ):
        if isinstance(block, int) and block < 0:
            block = self._chain_interface.get_block_number() + 1 + block

        tx_params = self._build_transaction(
            RequestType.ACCESS_LIST, params, arguments, abi, block
        )
        try:
            response = self._chain_interface.create_access_list(tx_params, block)
            return {
                Address(e["address"]): [int(s, 16) for s in e["storageKeys"]]
                for e in response["accessList"]
            }, int(response["gasUsed"], 16)
        except JsonRpcError as e:
            raise resolve_call_error(self, tx_params, block, e) from None

    @check_connected
    def _transact(
        self,
        abi: Optional[Dict],
        arguments: Iterable,
        params: TxParams,
        return_tx: bool,
        return_type: Type,
        confirmations: Optional[int],
        from_: Optional[Union[Account, Address, str]],
    ) -> Any:
        tx_params = self._build_transaction(
            RequestType.TX, params, arguments, abi, "pending"
        )

        tx_hash = self._send_transaction(tx_params, from_)

        if "type" not in tx_params:
            from wake.development.transactions import LegacyTransaction

            tx_type = LegacyTransaction[return_type]
        elif tx_params["type"] == 1:
            from wake.development.transactions import Eip2930Transaction

            tx_type = Eip2930Transaction[return_type]
        elif tx_params["type"] == 2:
            from wake.development.transactions import Eip1559Transaction

            tx_type = Eip1559Transaction[return_type]
        elif tx_params["type"] == 4:
            from wake.development.transactions import Eip7702Transaction

            tx_type = Eip7702Transaction[return_type]
        else:
            raise ValueError(f"Unknown transaction type {tx_params['type']}")

        tx = tx_type(
            tx_hash,
            tx_params,
            abi,
            return_type,
            self,
        )

        if confirmations != 0:
            tx.wait(confirmations)

            coverage_handler = get_coverage_handler()
            if coverage_handler is not None:
                tx._fetch_debug_trace_transaction()
                coverage_handler.add_coverage(
                    tx_params,
                    tx.block.number,
                    self,
                    tx._debug_trace_transaction,  # pyright: ignore reportGeneralTypeIssues
                )

            if self.tx_callback is not None:
                self.tx_callback(tx)

            if tx.error is not None:
                raise tx.error

        if return_tx:
            return tx

        return tx.return_value


@contextmanager
def _signer_account(sender: Account):
    chain = sender.chain
    chain_interface = chain.chain_interface
    account_created = True
    if sender not in chain.accounts:
        account_created = False
        if isinstance(chain_interface, (AnvilChainInterface, HardhatChainInterface)):
            chain_interface.impersonate_account(str(sender))
        else:
            raise NotImplementedError()

    try:
        yield
    finally:
        if not account_created and isinstance(
            chain_interface, (AnvilChainInterface, HardhatChainInterface)
        ):
            chain_interface.stop_impersonating_account(str(sender))


def get_fqn_from_creation_code(creation_code: bytes) -> Tuple[str, int]:
    original_creation_code = creation_code

    for creation_code_segments, fqn in creation_code_index:
        creation_code = original_creation_code

        length, h = creation_code_segments[0]
        if length > len(creation_code):
            continue
        segment_h = BLAKE2b.new(data=creation_code[:length], digest_bits=256).digest()
        if segment_h != h:
            continue

        creation_code = creation_code[length:]
        found = True
        constructor_offset = length

        for length, h in creation_code_segments[1:]:
            if length + 20 > len(creation_code):
                found = False
                break
            creation_code = creation_code[20:]
            segment_h = BLAKE2b.new(
                data=creation_code[:length], digest_bits=256
            ).digest()
            if segment_h != h:
                found = False
                break
            creation_code = creation_code[length:]
            constructor_offset += length + 20

        if found:
            return fqn, constructor_offset

    raise ValueError("Could not find contract definition from creation code")


def get_fqn_from_address(
    addr: Address, block_number: Union[int, str], chain: Chain
) -> Optional[str]:
    code = chain.chain_interface.get_code(str(addr), block_number)
    metadata_length = int.from_bytes(code[-2:], "big")
    metadata = code[-metadata_length - 2 : -2]
    if metadata in contracts_by_metadata:
        return contracts_by_metadata[metadata]
    else:
        return None


def get_contract_from_fqn(fqn: str):
    return contracts_by_fqn[fqn]
