import asyncio
import inspect
import json
import logging
from pathlib import Path, PurePath, PurePosixPath, PureWindowsPath

from wake.compiler.compiler import (
    ProjectBuild,
    SolcOutputSelectionEnum,
    SolidityCompiler,
)
from wake.config import WakeConfig
from wake.utils import is_relative_to

from .common import McpBuild


# performs one-time compilation of a project from sources.json generated by wake open --export json
class JsonCompiler:
    _logger: logging.Logger
    _ready: asyncio.Event
    _json_file: Path
    _execution_root: Path
    _build: ProjectBuild
    _config: WakeConfig
    _relative_compilation_root: Path
    _original_project_root: PurePath

    def __init__(self, json_file: Path, execution_root: Path, logger: logging.Logger):
        self._ready = asyncio.Event()
        self._json_file = json_file
        self._execution_root = execution_root
        self._logger = logger

    def is_ready(self) -> bool:
        return self._ready.is_set()

    async def get_config(self) -> WakeConfig:
        await self._ready.wait()
        return self._config

    async def get_build(self) -> McpBuild:
        await self._ready.wait()
        return McpBuild(
            project_root=Path(self._original_project_root),
            relative_compilation_root=self._relative_compilation_root,
            source_units=self._build.source_units,
            interval_trees=self._build.interval_trees,
            reference_resolver=self._build.reference_resolver,
        )

    async def run(self):
        loaded = json.loads(self._json_file.read_text())

        self._relative_compilation_root = Path(
            loaded.get("relative_compilation_root", "./")
        )

        if loaded["system"] == "Windows":
            wake_contracts_path = PureWindowsPath(loaded["wake_contracts_path"])
            self._original_project_root = PureWindowsPath(loaded["project_root"])
        else:
            wake_contracts_path = PurePosixPath(loaded["wake_contracts_path"])
            self._original_project_root = PurePosixPath(loaded["project_root"])

        config = WakeConfig.fromdict(
            loaded["config"],
            wake_contracts_path=wake_contracts_path,
            paths_mode=loaded["system"],
        )

        self._config = config

        modified_files = {
            Path(path): source["content"].encode("utf-8")
            for path, source in loaded["sources"].items()
        }
        files = {
            path
            for path in modified_files.keys()
            if not any(
                is_relative_to(path, p) for p in config.compiler.solc.exclude_paths
            )
        }
        symlinks = {
            PurePath(k): PurePath(v) for k, v in loaded.get("symlinks", {}).items()
        }

        compiler = SolidityCompiler(config)
        compiler.load()

        kwargs = {}
        sig = inspect.signature(compiler.compile)
        if "virtual_root" in sig.parameters:
            kwargs["virtual_root"] = Path(self._original_project_root)
        if "virtual_symlinks" in sig.parameters:
            kwargs["virtual_symlinks"] = symlinks

        self._build, _ = await compiler.compile(
            files,
            [SolcOutputSelectionEnum.ALL],
            modified_files=modified_files,
            write_artifacts=False,
            **kwargs,
        )

        self._ready.set()
